services:
  # Web Service (API NestJS)
  - type: web
    name: foodly-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: foodly-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 7d
      - key: CORS_ORIGIN
        value: "*"

  # PostgreSQL Database
  - type: pserv
    name: foodly-db
    env: docker
    region: frankfurt
    plan: free
    disk:
      name: foodly-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
