services:
  # Web Service (API NestJS)
  - type: web
    name: foodly-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy && npx ts-node prisma/seed.ts
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: foodly-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 7d
      - key: CORS_ORIGIN
        value: "*"

databases:
  # PostgreSQL Database
  - name: foodly-db
    databaseName: foodly_db
    user: foodly_user
    region: frankfurt
    plan: free
